// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace GradjFirma.Migrations
{
    [DbContext(typeof(FirmaContext))]
    partial class FirmaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Firma", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MB")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PIB")
                        .HasColumnType("int");

                    b.Property<string>("Zastupnik")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Firma");
                });

            modelBuilder.Entity("Models.Masina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojRadnihSati")
                        .HasColumnType("int");

                    b.Property<int?>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("Godiste")
                        .HasColumnType("int");

                    b.Property<int>("IdentifikacioniBroj")
                        .HasColumnType("int");

                    b.Property<int>("RadnikFK")
                        .HasColumnType("int");

                    b.Property<string>("Stanje")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID");

                    b.HasIndex("FirmaID");

                    b.ToTable("Masina");
                });

            modelBuilder.Entity("Models.Projekat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojProjekta")
                        .HasColumnType("int");

                    b.Property<int>("BrojRadnika")
                        .HasColumnType("int");

                    b.Property<int?>("FirmaID")
                        .HasColumnType("int");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TipProjekta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("FirmaID");

                    b.ToTable("Projekat");
                });

            modelBuilder.Entity("Models.Radnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojGodina")
                        .HasColumnType("int");

                    b.Property<int?>("FirmaID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("IskustvoGod")
                        .HasColumnType("int");

                    b.Property<int>("Jmbg")
                        .HasColumnType("int");

                    b.Property<string>("Masina")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Profesija")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProjekatID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FirmaID");

                    b.HasIndex("ProjekatID");

                    b.ToTable("Radnik");
                });

            modelBuilder.Entity("Models.Masina", b =>
                {
                    b.HasOne("Models.Firma", "Firma")
                        .WithMany("SveMasine")
                        .HasForeignKey("FirmaID");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("Models.Projekat", b =>
                {
                    b.HasOne("Models.Firma", "Firma")
                        .WithMany("SviProjekti")
                        .HasForeignKey("FirmaID");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("Models.Radnik", b =>
                {
                    b.HasOne("Models.Firma", "Firma")
                        .WithMany("SviRadnici")
                        .HasForeignKey("FirmaID");

                    b.HasOne("Models.Projekat", "Projekat")
                        .WithMany("SpisakRadnika")
                        .HasForeignKey("ProjekatID");

                    b.Navigation("Firma");

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("Models.Firma", b =>
                {
                    b.Navigation("SveMasine");

                    b.Navigation("SviProjekti");

                    b.Navigation("SviRadnici");
                });

            modelBuilder.Entity("Models.Projekat", b =>
                {
                    b.Navigation("SpisakRadnika");
                });
#pragma warning restore 612, 618
        }
    }
}
